// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"myapp/internal/config"
	"myapp/internal/infrastructure/repository/gorm"
	"myapp/internal/presentation/hello"
	"myapp/internal/usecase"
)

// Injectors from wire.go:

func InjectAPI(config2 *config.Config) (*API, error) {
	helloWorldRepository := gorm.NewHelloWorldRepository()
	getHelloUsecase := usecase.NewGetHelloUsecase(helloWorldRepository)
	handler := hello.NewHandler(getHelloUsecase)
	api := NewAPI(handler)
	return api, nil
}
